import { expect, test } from "@playwright/test";
import { signInThroughUI } from "./auth";

test("bind a knowledge connection and search lexical, semantic and hybrid context", async ({ page }) => {
  const identity = await signInThroughUI(page);
  const headers = { "x-csrf-token": identity.csrf_token };
  const resource = await page.request.post("/api/v1/resources", { headers, data: { kind: "connection", name: "Knowledge connector", slug: "knowledge-connector", spec: { adapter: "http", base_url: "https://knowledge.example.test", description: "Offline configured connector" } } });
  expect(resource.status()).toBe(201); const item = await resource.json();
  expect((await page.request.post(`/api/v1/resources/${item.id}/publish`, { headers, data: { revision: item.revision } })).status()).toBe(201);
  const embedding = await page.request.post("/api/v1/resources", { headers, data: { kind: "embedding", name: "Local vectors", slug: "local-vectors", spec: { provider: "local", model: "local-hash", dimensions: 96 } } });
  expect(embedding.status()).toBe(201); const embeddingItem = await embedding.json();
  expect((await page.request.post(`/api/v1/resources/${embeddingItem.id}/publish`, { headers, data: { revision: embeddingItem.revision } })).status()).toBe(201);
  await page.getByRole("button", { name: "08 Knowledge", exact: true }).click();
  await page.getByRole("button", { name: "New collection" }).first().click();
  const collection = page.getByRole("form", { name: "Create collection" });
  await collection.getByLabel("Name", { exact: true }).fill("Product manuals");
  await collection.getByLabel("Description", { exact: true }).fill("Semantic retrieval examples");
  await collection.getByLabel("Connection").selectOption(item.id);
  await collection.getByLabel("Embedding provider").selectOption(embeddingItem.id);
  await collection.getByRole("button", { name: "Create collection", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Collection created");
  await page.getByRole("button", { name: "Index document", exact: true }).click();
  const document = page.getByRole("form", { name: "Index document" });
  await document.getByLabel("Title", { exact: true }).fill("Reset procedure");
  await document.getByLabel("Source URI", { exact: true }).fill("manual://reset");
  await document.getByLabel("Content", { exact: true }).fill("The vehicle can restart after a safe engine reset procedure.");
  await document.getByRole("button", { name: "Index document", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Document indexed");
  const search = page.getByRole("form", { name: "Search indexed context" });
  await search.getByPlaceholder("Search this collection…").fill("engine restart");
  await search.getByLabel("Retrieval mode").selectOption("semantic");
  await search.getByRole("button", { name: "Search", exact: true }).click();
  await expect(page.getByText("Reset procedure", { exact: true })).toBeVisible();
  await expect(page.getByText(/semantic/)).toBeVisible();
  await search.getByLabel("Retrieval mode").selectOption("lexical");
  await search.getByRole("button", { name: "Search", exact: true }).click();
  await expect(page.getByText("manual://reset", { exact: true })).toBeVisible();
  await expect(page.getByText(/Collection created/)).toHaveCount(0);
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.screenshot({ path: "/tmp/eivon-knowledge-populated-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  await page.screenshot({ path: "/tmp/eivon-knowledge-populated-mobile.png", fullPage: true });
});
