export const zhCN: Record<string, string> = {
  // Navigation and common controls
  "Overview": "总览", "Agents": "智能体", "Resources": "资源", "Resource library": "资源库",
  "Workflows": "工作流", "Playground": "对话台", "Run history": "运行记录", "Evaluations": "评测中心",
  "Knowledge": "知识库", "Members": "成员", "Settings": "设置", "Workspace": "工作区",
  "Current workspace": "当前工作区", "Local instance": "本地实例", "CONTROL PLANE /": "控制台 /",
  "CONTROL PLANE / ": "控制台 / ", "WORKSPACE NAVIGATION": "工作区导航", "Main navigation": "主导航",
  "WORKBENCH": "工作台", "AGENT WORKBENCH": "智能体工作台",
  "Sign out": "退出登录", "Reload available workspace": "重新加载工作区",
  "Switching workspace…": "正在切换工作区…", "Loading Eivon…": "正在加载 Eivon…",
  "Create your workspace": "创建工作区", "Welcome back": "欢迎回来",
  "Set up the first administrator for this self-hosted instance.": "为此自托管实例创建首位管理员。",
  "Sign in to manage your agents.": "登录以管理智能体。", "Setup token": "初始化令牌",
  "Your name": "你的姓名", "Workspace name": "工作区名称", "Email": "邮箱", "Password": "密码",
  "Initialize Eivon": "初始化 Eivon", "Sign in": "登录", "Name": "名称", "Description": "描述",
  "INITIAL SETUP": "初始配置", "ACCOUNT ACCESS": "账户登录", "Self-hosted agent workbench": "自托管智能体工作台",
  "Show password": "显示密码", "Hide password": "隐藏密码", "Initializing…": "正在初始化…", "Signing in…": "正在登录…",
  "Title": "标题", "Content": "内容", "Search": "搜索", "Refresh": "刷新", "Previous": "上一页",
  "Next": "下一页", "of": "共", "Updated": "更新于", "Close": "关闭", "State": "状态",
  "Status": "状态", "Version": "版本", "Role": "角色", "Type": "类型", "Output": "输出",
  "Active": "启用", "Archived": "已归档", "DRAFT": "草稿", "ARCHIVED": "已归档",
  "Draft": "草稿", "Published": "已发布", "EIVON": "EIVON", "Eivon": "Eivon",
  "English": "English", "简体中文": "简体中文", "Language": "语言", "Interface language": "界面语言",
  "Choose the language used across the console.": "选择控制台的显示语言。",
  // Overview
  "A SYSTEM FOR BUILDING SYSTEMS": "智能体控制台", "Turn intent into": "让想法成为", "capability.": "可运行的能力。",
  "WORKSPACE STATUS": "工作区状态", "Build with clarity.": "清晰掌握每一步。",
  "Your agents, resources and execution history in one place.": "智能体、资源和运行记录都在这里。",
  "RECENT ACTIVITY": "最近动态", "Latest runs": "最近运行", "View all": "查看全部",
  "No runs yet.": "还没有运行记录。", "QUICK ACTIONS": "快捷操作",
  "Continue building": "继续工作", "Manage resources": "管理资源",
  "Open workflow studio": "打开工作流工作台", "Review evaluations": "查看评测",
  "Create an Agent release from model and prompt resources.": "从模型和提示词资源创建智能体版本。",
  "Configure models, tools, skills and workflows into agents that can reason, act and be observed.": "组合模型、工具、技能与工作流，发布可执行、可观测的智能体。",
  "Open Playground": "打开对话台", "ACTIVE RESOURCES": "活跃资源", "in this workspace": "当前工作区",
  "EXECUTION RUNS": "累计运行", "all time": "全部时间", "RUNTIME": "运行环境", "LOCAL": "本地",
  "self-hosted control plane": "自托管控制台", "VERSION": "版本", "foundation release": "基础版本",
  "GET STARTED": "快速开始", "Build your first agent": "创建第一个智能体",
  "Connect a model": "连接模型", "Choose a provider and test the connection →": "选择服务商并验证连接 →",
  "Add a capability": "添加能力", "Define a tool, skill or knowledge source →": "配置工具、技能或知识源 →",
  "Publish an agent": "发布智能体", "Compose resources and freeze a release →": "组合资源并发布固定版本 →",
  // Knowledge
  "GROUNDED CONTEXT": "知识上下文", "collections": "个知识集合", "Create collection": "创建知识集合",
  "Collections": "知识集合", "collection": "个知识集合", "New collection": "新建集合", "No collections yet": "还没有知识集合",
  "Create a collection to organize your sources.": "创建集合，整理并检索你的知识来源。",
  "Connected source": "已连接来源", "COLLECTION": "知识集合", "DOCUMENT": "文档", "Cancel": "取消",
  "Searching…": "搜索中…", "Search results": "搜索结果", "result": "条结果", "results": "条结果",
  "No matching documents": "没有匹配的文档", "Search this collection": "检索此集合",
  "Try another query or retrieval mode.": "试试其他关键词或检索模式。", "Indexed results will appear here.": "索引后的检索结果会显示在这里。",
  "Bind an optional versioned HTTP/MCP connection and embedding provider.": "可绑定已发布的 HTTP/MCP 连接和向量模型。",
  "Connection": "连接", "Local documents": "本地文档", "Embedding provider": "向量模型",
  "Local feature hashing": "本地特征哈希", "Index document": "索引文档", "Collection": "知识集合",
  "Choose collection": "选择知识集合", "Source URI": "来源地址", "Sync connection": "同步连接",
  "Search indexed context": "检索知识内容", "Search this collection…": "搜索此知识集合…",
  "Retrieval mode": "检索模式", "Hybrid": "混合", "Semantic": "语义", "Lexical": "关键词",
  "Search results show source chunks with lexical and semantic scores.": "检索结果会显示内容片段、来源及相关性评分。",
  "score": "分", "semantic": "语义", "Connection check": "连接检查",
  // Resource library and editor
  "VERSIONED ASSETS": "版本化资源", "+ New resource": "+ 新建资源", "Search resources": "搜索资源",
  "Search names…": "搜索名称…", "Resource type": "资源类型", "All types": "全部类型",
  "Resource state": "资源状态", "No matching resources": "没有匹配的资源",
  "No resources yet": "还没有资源", "Create, publish and compose resources for your workspace.": "为工作区创建、发布和组合资源。",
  "Create resource": "创建资源", "NEW RESOURCE": "新建资源", "Slug": "标识符", "Template": "模板",
  "Provider": "服务商", "Offline demo": "离线演示", "OpenAI-compatible": "OpenAI 兼容接口",
  "Offline local": "本地离线", "Model": "模型", "Base URL": "接口地址", "Credential": "凭据",
  "No credential": "不使用凭据", "Create encrypted credentials in Settings. The deployment must allow the provider host.": "请在设置中创建加密凭据，并在部署配置中允许服务商域名。",
  "Specification JSON": "配置 JSON", "Published model": "已发布模型", "Choose a model": "选择模型",
  "Published system Prompt": "已发布系统提示词", "No prompt": "不使用提示词",
  "Use the draft editor to add tools, skills, bundles, knowledge and execution policy before publishing.": "发布前可在草稿编辑器中添加工具、技能、能力包、知识库和执行策略。",
  "Create draft": "创建草稿", "Edit resource": "编辑资源", "RESOURCE /": "资源 /",
  "Discard edits and reload": "放弃修改并重新加载", "Draft revision": "草稿修订版",
  "Active release": "当前发布版", "Resource draft": "资源草稿", "· Unsaved changes": " · 未保存的修改",
  "Draft JSON": "草稿 JSON", "Publishing saves these edits and creates a new immutable release.": "发布会保存当前修改，并创建不可变版本。",
  "Save draft": "保存草稿", "Publish release": "发布版本", "Validate saved draft": "校验已保存草稿",
  "Release history": "版本历史", "No published releases yet.": "还没有已发布版本。",
  "Release version": "发布版本", "Immutable specification and digest": "不可变配置与摘要",
  "Pinned dependencies": "固定依赖", "Activate v": "激活 v", "Use v": "使用 v", "as draft": "作为草稿",
  "Activating a release changes future Runs. It preserves both the saved draft and existing Run snapshots.": "激活版本只影响后续运行；已保存的草稿和现有运行快照不会改变。",
  "Compare with": "比较对象", "Editor draft": "编辑器草稿", "Specification differences": "配置差异",
  "No specification changes.": "配置没有变化。", "No published Agent": "没有已发布的智能体",
  // Workflow studio
  "ORCHESTRATION": "流程编排", "Workflow studio": "工作流工作台", "+ New workflow": "+ 新建工作流",
  "SAVED WORKFLOWS ·": "已保存工作流 ·", "No workflows yet.": "还没有工作流。",
  "Workflow input and output": "工作流输入与输出", "Input schema JSON": "输入 Schema JSON",
  "Output template": "输出模板", "Bind values with": "使用占位符引用", "or": "或",
  ". A whole placeholder keeps its JSON type.": "。完整占位符会保留 JSON 类型。",
  "Workflow view": "工作流视图", "Step editor": "步骤编辑", "Graph view": "流程图",
  "Step ID": "步骤 ID", "Question": "问题", "Response schema JSON": "响应 Schema JSON",
  "Arguments JSON": "参数 JSON", "Prompt template": "提示词模板", "Value path": "取值路径",
  "Equals JSON": "匹配值 JSON", "Skip selected later steps when the value matches:": "值匹配时跳过下列后续步骤：",
  "Move up": "上移", "Move down": "下移", "Remove step": "删除步骤",
  "Save and publish": "保存并发布", "Run published v": "运行已发布 v",
  "Runs use the published release. Save and publish to include your latest edits.": "运行使用已发布版本。请先保存并发布最新修改。",
  "Run input JSON": "运行输入 JSON", "Run published workflow": "运行已发布工作流",
  "Workflow graph": "工作流图", "Execution graph": "执行流程图",
  "Ordered flow with conditional skip edges": "按顺序执行，条件节点可跳过后续步骤",
  "Add steps to see the graph.": "添加步骤后会显示流程图。", "Tool ·": "工具 ·",
  "Model ·": "模型 ·", "skips →": "跳过 →", "Choose published": "选择已发布资源",
  "(unavailable)": "（不可用）",
  // Playground, Runs and artifacts
  "LIVE RUNTIME": "实时运行", "New conversation": "新建对话", "Saved conversations": "已保存对话",
  "CONVERSATIONS": "对话记录", "Your conversations appear here.": "你的对话会显示在这里。",
  "Conversation": "对话", "Conversation messages": "对话消息", "You": "你",
  "Inspect turn · v": "查看回合 · v", "Choose a published Agent. Conversations are saved and can be reopened later.": "请选择已发布智能体。对话会自动保存，可随时重新打开。",
  "Agent": "智能体", "Choose published Agent": "选择已发布智能体", "Saved Agent (unavailable)": "已保存的智能体（不可用）",
  "Business context": "业务上下文", "Context JSON": "上下文 JSON", "Message": "消息",
  "Ask your agent something…": "给智能体发送消息…", "Send message": "发送消息",
  "A run is active. Use its controls below to approve, resume or cancel.": "任务正在运行，可在下方审批、继续或取消。",
  "OBSERVABILITY": "运行观察", "All statuses": "全部状态", "RUN": "运行 ID",
  "STATUS": "状态", "CREATED": "创建时间", "No matching runs.": "没有匹配的运行记录。",
  "Run details": "运行详情", "Refresh run": "刷新运行", "Required input schema": "所需输入 Schema",
  "Response JSON": "响应 JSON", "Resume workflow": "继续工作流", "Approve": "批准",
  "Decline": "拒绝", "Cancel run": "取消运行", "Live response": "实时回复",
  "Generated files": "生成的文件", "bytes": "字节", "Release dependencies · v": "版本依赖 · v",
  "Execution timeline ·": "执行时间线 ·", "events": "个事件",
  // Evaluations
  "Evaluation center": "评测中心", "Refresh evaluations": "刷新评测", "Create evaluation set": "创建评测集",
  "Create test set": "创建测试集", "Cases JSON": "用例 JSON",
  "Each case has input, expected and match: contains, exact or nonempty. Saved sets are immutable.": "每个用例包含 input、expected 和 match（contains、exact 或 nonempty）；保存后不可修改。",
  "Save test set": "保存测试集", "Run evaluation": "运行评测", "Published release": "已发布版本",
  "Test set": "测试集", "Choose test set": "选择测试集", "Published Agent": "已发布智能体",
  "Choose Agent": "选择智能体", "Choose version": "选择版本", "Evaluation history": "评测历史",
  "Batch history": "批次历史", "Administrators can inspect all workspace batches; other members see their own executions.": "管理员可查看工作区全部批次，其他成员只能查看自己运行的评测。",
  "No evaluation batches yet.": "还没有评测批次。", "Previous batches": "上一批", "Next batches": "下一批",
  "batches": "个批次", "Evaluation details": "评测详情", "Batch": "批次",
  "Rule score:": "规则得分：", "passed": "通过", "Compare evaluations": "比较评测",
  "Compare releases": "比较版本", "Select completed batches from the same Agent and test set. Rule scores remain separate from human review.": "请选择同一智能体、同一测试集的已完成批次；规则得分和人工评分分别记录。",
  "Baseline batch": "基线批次", "Choose baseline": "选择基线", "Candidate batch": "候选批次",
  "Choose candidate": "选择候选批次", "Compare batches": "比较批次",
  "Evaluation comparison": "评测对比", "Score change:": "得分变化：", "improved ·": "提升 ·",
  "regressed": "下降", "Case": "用例", "Expected:": "期望：", "· Expected:": " · 期望：",
  "Human:": "人工：", "Human review:": "人工评审：", "· rule": " · 规则",
  "Add human review": "添加人工评审", "Human score": "人工评分", "Review note": "评审备注",
  "Save human review": "保存人工评审", "Reflection and improvements": "复盘与改进",
  "Model generated analysis": "模型生成分析", "Model analysis": "模型分析",
  "Suggested instruction": "建议指令", "Use suggestion in proposal": "将建议用于提案",
  "Raw model output": "模型原始输出",
  "This report summarizes test evidence. Author an instruction candidate for review; approval updates only its draft. Publish the dependency and a new Agent release, then rerun this test set to measure the effect.": "报告汇总测试证据。提交指令改进提案并经审批后，才会更新草稿；发布依赖和新的智能体版本后，请重新运行该测试集验证效果。",
  "Propose improvement": "提交改进提案", "Instruction resource": "指令资源",
  "Choose a Prompt or Skill": "选择提示词或技能", "· evaluated v": " · 评测版本 v",
  "· draft r": " · 草稿修订 r", "Current draft instructions": "当前草稿指令",
  "Proposed instructions": "建议指令", "Rationale": "改进理由", "Submit candidate": "提交候选方案",
  "This release has no Prompt or Skill dependency to improve.": "此版本没有可改进的提示词或技能依赖。",
  "Candidate ·": "候选方案 ·", "Based on draft r": "基于草稿修订 r",
  "Inspect proposed change": "查看建议变更", "Before": "修改前", "After": "修改后",
  "Decision:": "决定：", "Decision note": "审批备注", "Accept into draft": "接受并写入草稿",
  "Reject candidate": "拒绝候选方案",
  // Administration
  "Workspace members": "工作区成员", "members": "位成员", "Add member": "添加成员",
  "Add a member": "添加成员", "New accounts require an initial password of at least 12 characters. For an existing account, leave it blank; its name and password stay unchanged.": "新账号需要至少 12 位初始密码。添加已有账号时可留空，姓名和密码会保持不变。",
  "Initial password": "初始密码", "Member list": "成员列表", "Access roles": "访问角色",
  "Owner/admin: manage; editor: author and run; operator: run and approve; viewer: read. Only owners can manage administrators.": "所有者和管理员可管理；编辑者可编写并运行；操作员可运行和审批；访客只读。只有所有者能管理管理员。",
  "Member role": "成员角色", "Save role": "保存角色", "Remove member": "移除成员",
  "Workspace settings": "工作区设置", "Refresh access": "刷新权限", "Signed in as": "当前登录：",
  "Permissions:": "权限：", "Rename workspace": "重命名工作区", "Create workspace": "创建工作区",
  "Start a separate space with its own resources, conversations, members and credentials.": "创建独立空间，分别管理资源、对话、成员和凭据。",
  "Credential editor": "凭据管理", "Rotate credential": "轮换凭据", "Encrypted credentials": "加密凭据",
  "Rotation replaces the secret while preserving its ID and resource references. Stored values are never displayed.": "轮换会替换密钥内容，但保留凭据 ID 和资源引用；已保存的密钥不会再次显示。",
  "Credential name": "凭据名称", "Secret value": "密钥内容", "Save rotation": "保存轮换",
  "Save credential": "保存凭据", "Cancel rotation": "取消轮换", "Rotate": "轮换",
  "API key management": "API Key 管理", "Workspace API keys": "工作区 API Key",
  "Key name": "Key 名称", "Expires in days": "有效天数", "Create API key": "创建 API Key",
  "Copy this secret now. It will not be returned again.": "请立即保存密钥，之后无法再次查看。",
  "Hide secret": "隐藏密钥", "Revoke key": "撤销 Key", "Workspace audit log": "工作区审计日志",
  "Refresh audit": "刷新审计", "· actor": " · 操作人", "Event details": "事件详情",
  "No events yet.": "还没有审计事件。",
  // Dynamic state and feedback
  "Member added": "成员已添加", "Member role updated": "成员角色已更新",
  "Member removed; workspace API keys revoked": "成员已移除，工作区 API Key 已撤销",
  "Workspace renamed": "工作区已重命名", "Workspace created": "工作区已创建",
  "Credential rotated": "凭据已轮换", "Credential saved": "凭据已保存",
  "API key created": "API Key 已创建", "API key revoked": "API Key 已撤销",
  "Collection created": "知识集合已创建", "Document indexed": "文档已索引",
  "Synced {imported} documents · {skipped} unchanged": "已同步 {imported} 篇文档，{skipped} 篇未变化",
  "owner": "所有者", "admin": "管理员", "editor": "编辑者", "operator": "操作员", "viewer": "访客",
  "read": "读取", "write": "编辑", "execute": "运行", "approve": "审批", "expires": "到期于",
  "expired": "已过期", " · you": " · 你", "draft": "草稿", "completed": "已完成",
  "failed": "失败", "cancelled": "已取消", "queued": "排队中", "running": "运行中",
  "waiting_input": "等待输入", "waiting_approval": "等待审批", "cancelling": "正在取消",
  "loading": "加载中", "pending": "待处理", "accepted": "已接受", "rejected": "已拒绝",
  "timed_out": "已超时", "improved": "提升",
  "model": "模型", "embedding": "向量模型", "prompt": "提示词", "tool": "工具",
  "skill": "技能", "bundle": "能力包", "workflow": "工作流", "agent": "智能体",
  "connection": "连接", "input": "输入", "condition": "条件", "unbound": "未绑定",
  "Input": "输入", "Tool": "工具", "Prompt": "提示词", "Condition": "条件",
  "New workflow": "新建工作流", "Run": "运行", "Provide input": "请提供输入",
  "tool execution": "工具执行",
  "Inspect evaluation {id}": "查看评测 {id}",
  "Evaluation case {number}": "评测用例 {number}",
  "Improvement {id}": "改进提案 {id}",
  "Inspect run {id}": "查看运行 {id}", "Step {number}": "步骤 {number}",
  "contains": "包含", "exact": "完全匹配", "nonempty": "非空",
  "Active run": "运行中", "Saved": "已保存", "Not published": "尚未发布",
  "Restore resource": "恢复资源", "Archive resource": "归档资源",
  "Enter a resource name": "请输入资源名称", "Response must be a JSON object": "响应必须是 JSON 对象",
  "Business context must be a JSON object": "业务上下文必须是 JSON 对象",
  "Candidate": "候选版本", "Baseline": "基线版本", "No output": "无输出",
  "Analyzing…": "分析中…", "Regenerate model analysis": "重新生成模型分析",
  "Generate model analysis": "生成模型分析", "· structured": " · 结构化结果",
  "· raw provider output": " · 服务商原始输出",
  "Model analysis saved to this evaluation batch": "模型分析已保存到当前评测批次",
  "Suggestion copied into the proposal form; review it before submitting": "建议已填入提案表单，请检查后提交",
  "Candidate submitted for administrator review": "候选方案已提交管理员审核",
  "Release published": "版本已发布", "Draft saved": "草稿已保存",
  "Published v{version}": "已发布 v{version}", "Draft revision {revision}": "草稿修订版 {revision}",
  "Add at least one step": "请至少添加一个步骤", "Step IDs must be unique": "步骤 ID 不能重复",
  "Latest saved draft loaded": "已加载最新保存的草稿",
  "Active release changed to v{version}. Existing Runs retain their snapshots.": "当前发布版已切换至 v{version}；现有运行仍保留原快照。",
  "Saved draft is valid · {count} pinned dependencies": "草稿校验通过 · {count} 项固定依赖",
  "Copied v{version} into the editor. Save or publish to persist it.": "已将 v{version} 复制到编辑器；保存或发布后才会生效。",
  " · unpublished": " · 未发布", " · connected": " · 已连接", " · local": " · 本地",
  " · active": " · 当前版本", "· v": " · v", "→ v": "→ v",
};
